export default {
  skip: "SKIP",
  Onboarding1_3_header: "Smart Profile and Post Targeting",
  Onboarding1_3_text: "uses AI to find ideal people and posts for you to engage with.",
  next: "Next",
  Onboarding1_4_header: "Get Daily Alert To Drive Maximum Followers",
  Onboarding1_4_text: "will present profiles to you each day so you never miss an opportunity to gain new followers.",
  Onboarding1_5_header: "Watch Your Page Grow",
  Onboarding1_5_text: "Get up to date stats and adjust your growth settings to maximize growth.",
  lets_get_started: "Let's Get Started",
  Android_Mobile_1_text: "Grow your Instagram account for free",
  getStarted: "Get Started",
  aleady_have_account: "I already have an account",
  signUp: "Sign Up",
  firstName: "First Name",
  lastName: "Last Name",
  email: "Email",
  password: "Password",
  confirmPassword: "Confirm Password",
  have_account: "Have an account?",
  signIn: "Sign In",
  forgotPassword: "Forgot password?",
  dont_have_account: "Don't have an account?",
  or_connect_using: "Or connect using",
  add_ig_username: "Add Your IG Username",
  igUsername: "Instagram Username",
  can_change_settings_later: "You can always change settings later",
  how_use_ig_username: "How We Use Your Instagram Username?",
  how_use_ig_username_text: "The Growth Pal AI uses your Instagram username to understand your page, and to find the most targeted people and posts for you to engage with.",
  confirm_account: "Confirm your account",
  confirm_account_button: "This is me",
  finding_related_hashtags: "is working to find related hashtags for you",
  addHashtags: "Add Hashtags",
  how_use_hashtags: "How does Growth Pal use hashtags?",
  how_use_hashtags_text: "By adding hashtags, you are letting the Growth Pal AI know what topics are most important to you. This helps to refine the user target lists that are generated.",
  addTags: "Add Tags",
  cancel: "Cancel",
  enter_hashtag: "Enter a Hashtag",
  addTag: "Add Tag",
  select_time_zone: "Select a Time Zone",
  add_time_zone: "Add Time Zone",
  why_need_time_zone: "Why does Growth Pal need Time Zone?",
  why_need_time_zone_text: "Growth Pal must know when he can communicate with you and send you posts to like or accounts to follow. Set the time zone so it knows your day and night times.",
  search_city_zone: "Search City/Zone",
  finish: "Finish",
  howdy: "Howdy",
  finding_new_people_posts: "is finding new people and posts for you to engage with.",
  good_news: "Good news!",
  found_profiles_to_follow: "found profiles for you to follow.",
  click: "Click",
  follow_button_next_posts: " button to get started, or hit NEXT to view suggested posts.",
  follow: "Follow",
  found_posts_to_engage: " found X posts for you to engage with!",
  like: "Like",
  like_button_visit_dashboard: "the button to get started, or visit your Dashboard for more settings.",
  go_dashboard: "Go to Dashboard",
  dashboard: "Dashboard",
  dashboard_text: "View progress and daily notifications to guide you to Instagram stardom.",
  follow_unfollow: "Follow/Unfollow",
  follow_unfollow_text: " generates fresh new lists for you each day. The more you follow, the smarter Growth Pal becomes at suggesting the most suitable profiles.",
  posts_to_like: "Posts to Like",
  posts_to_like_text_begin: "Engaging with content is the best way to make a new friend. ",
  posts_to_like_text_end: " presents your daily dose of posts to like or comment on right here.",
  statistics: "Statistics",
  statistics_text: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.",
  settings: "Settings",
  settings_text_begin: "Set a weekly follower growth goal and ",
  settings_text_end: " takes care of the rest. You can also update hashtags and account settings here.",
  hi: "Hi",
  get_going: "Let's get growing!",
  select_session_to_start: "Select a new or ongoing session to start generating activities and followers.",
  newSessions: "New Sessions",
  inProgress: "In Progress",
  completed: "Completed",
  profiles_to_follow: "profiles to follow",
  start: "Start",
  unfollow: "Unfollow",
  profiles_to_unfollow: "profiles to unfollow",
  seeAll: "See all",
  profilesVisited: " profiles visited",
  gotIt: "Got It",
  work_smart_hard: "Work smart, not hard!",
  to_grow_account_need_people: "To grow your account, you need people to see your account first. The follow strategy is one powerful strategy to do this. Our ",
  to_grow_account_need_people2: " will find people who would be interested in your niche. just tap on ",
  to_grow_account_need_people3: " and follow them in Instagram.",
  it_helps_like_posts: "It realy helps you to like posts within your niche or from your target audience. Our ",
  it_helps_like_posts2: " will find posts in your niche, just tap on ",
  it_helps_like_posts3: " and like posts in Instagram.",
  basicInfo: "Basic Information",
  posts_visited: "Posts you've visited",
  posts: "posts",
  profiles_visited: "Profiles you've visited",
  profiles: "profiles",
  hashtags: "Hashtags",
  timeZone: "Time Zone",
  notifications_reminders: "Notifications and Reminder",
  on: "On",
  growthGoals: "Growth Goals",
  upgradeNow: "Upgrade Now",
  grow: "Grow", 
  saveChanges: "Save Changes",
  new: "New",
  changePassword: "Change Password",
  getHelp: "Get help",
  about_growth: "About Growth Pal",
  logout: "Logout",
  fastGrow: "Fast Grow",
  superGrow: "Super Grow",
  followers_per_week: " followers per week",
  activities_day: " activities per day",
  follows_day: " follows per day",
  unfollows_day: " unfollows per day",
  likes_day: " likes per day",
  notifications: "Notifications",
  choose_days_notified: "Choose times in a day you want to be notified",
  choose_times_notified: "Choose times in a day you want to be notified",
  could_not_find_related: "Sorry, we couldn't find any related accounts, hit Add Tags to try again"
}